### ISSUE TITLE
Path to settings file broken

### ISSUE THREAD

**Issue by nidegen** [OpenMapper/OpenMapperDesktop#4]
Running on mac, I get this error
```
Failed to open settings file at: libs/OpenMapper/thirdparty/slam_engine/ORB_SLAM2/Vocabulary/webcam.yaml
```
also, qt creates a mac app bundle, so that the executable is in a subfolder of ./bin/

no priority, but we should keep this in mind

**Comment by gocarlos** [comment]
yes, we have to fix that in a better way, eventually we could export the path over cmake to a header file or something else, right now it dependends on from where the executable is started....

**Comment by gocarlos** [comment]
Or do you have another idea, how we could some that problem?

**Comment by nidegen** [comment]
in the long term, maybe have a own config file which contains all resource paths?

**Comment by nidegen** [comment]
but then again, how do we pass its own path.. lets maybe wait a bit until the api/usage settles a bit

**Comment by gocarlos** [comment]
@nidegen could you have a look at [this](https://github.com/OpenMapper/OpenMapper/pull/26) PR?
It would address this issue

**Comment by gocarlos** [comment]
Just wanted you to have a look on it, will need to clean the PR a bit and add some more functionality

**Comment by gocarlos** [comment]
This should be fixed after the merge mentioned above

**Comment by nidegen** [comment]
awesome
